### ISSUE TITLE
[OTP] Should backspace only navigate if input is empty?

### ISSUE THREAD

**Issue by evoactivity** [universal-ember/ember-primitives#254]
I'm not 100% decided on this, but I do feel hitting backspace, then typing a number breaks my expectation that I will replace the current value I just deleted, instead I replace the value in the input before the input I hit backspace in. Posting this to get your opinion.

Current behaviour

https://github.com/universal-ember/ember-primitives/assets/83799/1f326c1e-802b-4835-8655-affdd1184f02

Proposed behaviour

https://github.com/universal-ember/ember-primitives/assets/83799/1f38723b-6bbe-4330-ada2-7c1c16b0bd1e

**Comment by NullVoxPopuli** [comment]
I like the proposed behavior better -- I think it's more intuitive since the cursor is where you just were _and you can see it_ -- highlighting the previous text field kinda looks goofy.

I would accept a PR for this (or I can have a go at fixing this tomorrow).

(thanks a ton for opening so many issue reports, it's immensely helpful!)
